namespace Enums.Audio
{
	// ReSharper disable InconsistentNaming
	public enum EventType
	{
		MUSIC_Title,
		MUSIC_Background,
		MUSIC_ResearchFacility,
		
		AMBIENT_Birds,
		
		SFX_DISASTER_HeavyRain,
		SFX_DISASTER_WindBlowing,
		SFX_DISASTER_RainAndWind,
		SFX_DISASTER_Earthquake,
		SFX_DISASTER_EARTHQUAKE_Quake,
		SFX_DISASTER_Thunder,

		SFX_BUILDING_Soil,
		SFX_BUILDING_Foundation,
		SFX_BUILDING_BUILDING,
		SFX_BUILDING_UPGRADE,
		SFX_BUILDING_REPAIR,
		SFX_BUILDING_SOIL_Crack,
		SFX_BUILDING_FOUNDATION_Crack,
		SFX_BUILDING_BUILDING_Crack,
		SFX_BUILDING_CONSUMED,
		
		SFX_MONSTER_GROWL,
		
		SFX_CLICK,
		
		SFX_INVENTORY_CLOSE,
		SFX_INVENTORY_OPEN,
		
		SFX_COLLECTING_RENT,
		SFX_PAYING,
		
		SFX_POWERUP_KCAF,
		SFX_POWERUP_MEAT,
		SFX_POWERUP_FREEZETIME,
		
		SFX_ACHIEVEMENT_Unlocked,
		
		SFX_CAR_ENGINE,
		
	}
}